// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"","parentId":"3","id":"1","originPath":"/"},"2":{"path":"/","isWrapper":true,"id":"2"},"3":{"path":"","isWrapper":true,"parentId":"2","id":"3"},"4":{"path":"","parentId":"5","id":"4","originPath":"/"},"5":{"path":"/","isWrapper":true,"parentId":"1","id":"5"},"6":{"path":"","parentId":"7","id":"6","originPath":"/home"},"7":{"path":"/home","isWrapper":true,"parentId":"1","id":"7"},"8":{"path":"","parentId":"10","id":"8","originPath":"/edge"},"9":{"path":"/edge","isWrapper":true,"parentId":"1","id":"9"},"10":{"path":"","isWrapper":true,"parentId":"9","id":"10"},"11":{"path":"/psi","parentId":"1","id":"11"},"12":{"path":"/*","redirect":"/login","parentId":"1","id":"12"},"13":{"path":"/","redirect":"/login","id":"13"},"14":{"path":"","parentId":"16","id":"14","originPath":"/login"},"15":{"path":"/login","isWrapper":true,"id":"15"},"16":{"path":"","isWrapper":true,"parentId":"15","id":"16"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "modules__layout__layout.view" */'@/modules/layout/layout.view.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "wrappers__theme-wrapper" */'@/wrappers/theme-wrapper.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "wrappers__login-auth" */'@/wrappers/login-auth.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__new-home" */'@/pages/new-home.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "wrappers__center-auth" */'@/wrappers/center-auth.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__new-home" */'@/pages/new-home.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "wrappers__center-auth" */'@/wrappers/center-auth.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__edge" */'@/pages/edge.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "wrappers__basic-node-auth" */'@/wrappers/basic-node-auth.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "wrappers__p2p-login-auth" */'@/wrappers/p2p-login-auth.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__psi" */'@/pages/psi.tsx')),
'12': React.lazy(() => import( './EmptyRoute')),
'13': React.lazy(() => import( './EmptyRoute')),
'14': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "wrappers__theme-wrapper" */'@/wrappers/theme-wrapper.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "wrappers__login-wrapper" */'@/wrappers/login-wrapper.tsx')),
},
  };
}
